create index IX_1AB7AC68 on contato (accountId);
create index IX_5FFB95F7 on contato (cargoId);
create index IX_924285C5 on contato (classNameId, classPK);
create index IX_C8C9B6B8 on contato (companyId);
create index IX_C6CCD7AF on contato (companyId, cargoId);
create index IX_2C00B341 on contato (companyId, dataNascimento);
create index IX_CBE212ED on contato (companyId, endEmail);
create index IX_7711CCF2 on contato (companyId, groupId);
create index IX_51E122B5 on contato (companyId, groupId, cargoId);
create index IX_29D9157B on contato (companyId, groupId, dataNascimento);
create index IX_A35728A7 on contato (companyId, groupId, endEmail);
create index IX_48C683F on contato (companyId, groupId, nome);
create index IX_67036585 on contato (companyId, nome);
create index IX_D9B4D3F9 on contato (dataNascimento);
create index IX_588B1DA5 on contato (endEmail);
create index IX_F8E8C3D on contato (nome);

create index IX_3B60E668 on endereco (bairro);
create index IX_ABB8DF0F on endereco (cep);
create index IX_40F59FE7 on endereco (cidade);
create index IX_E3054F79 on endereco (companyId);
create index IX_35BCE92 on endereco (companyId, bairro);
create index IX_4BB0F725 on endereco (companyId, cep);
create index IX_8F08811 on endereco (companyId, cidade);
create index IX_AE05675 on endereco (companyId, classNameId);
create index IX_7D09F10E on endereco (companyId, classNameId, classPK);
create index IX_65AC3E90 on endereco (companyId, classNameId, classPK, principal);
create index IX_5D56A46A on endereco (companyId, groupId, bairro);
create index IX_97E1B04D on endereco (companyId, groupId, cep);
create index IX_62EB5DE9 on endereco (companyId, groupId, cidade);
create index IX_C5F9679D on endereco (companyId, groupId, classNameId);
create index IX_BA2639B on endereco (companyId, groupId, paisId);
create index IX_68072F96 on endereco (companyId, groupId, uf);
create index IX_B1A78DC3 on endereco (companyId, paisId);
create index IX_3C47ADBE on endereco (companyId, uf);
create index IX_E9ACA599 on endereco (paisId);
create index IX_F50E2094 on endereco (uf);
create index IX_7433C585 on endereco (uuid_);
create index IX_8EF40983 on endereco (uuid_, companyId);
create unique index IX_A5E714C5 on endereco (uuid_, groupId);

create index IX_9DC54ABC on endereco_email (companyId);
create index IX_903C0012 on endereco_email (companyId, classNameId);
create index IX_1AC6C811 on endereco_email (companyId, classNameId, classPK);
create index IX_6367F7AD on endereco_email (companyId, classNameId, classPK, principal);
create index IX_5161DA48 on endereco_email (uuid_);
create index IX_6426CE0 on endereco_email (uuid_, companyId);
create unique index IX_8D40AB62 on endereco_email (uuid_, groupId);

create index IX_FA1E29F8 on telefone (companyId);
create index IX_2580C256 on telefone (companyId, classNameId);
create index IX_BD3E524D on telefone (companyId, classNameId, classPK);
create index IX_F158EFF1 on telefone (companyId, classNameId, classPK, principal);
create index IX_8A3B784 on telefone (uuid_);
create index IX_15C73224 on telefone (uuid_, companyId);
create unique index IX_16FDF1A6 on telefone (uuid_, groupId);