create table loja (
	uuid_ VARCHAR(75) null,
	lojaId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	createUserId LONG,
	modifiedUserId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	razaoSocial VARCHAR(200) null,
	nomeFantasia VARCHAR(100) null,
	observacao STRING null,
	cnpj VARCHAR(75) null,
	endLogradouro VARCHAR(100) null,
	endNumero VARCHAR(75) null,
	endComplemento VARCHAR(75) null,
	endCep VARCHAR(75) null,
	endBairro VARCHAR(75) null,
	endCidade VARCHAR(75) null,
	endUf VARCHAR(2) null,
	endPais VARCHAR(75) null,
	versao DOUBLE,
	ordemIndicada INTEGER,
	ordemIndicadaAtual BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	classNameId LONG,
	classPK LONG
);