/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.lapidarios.lojaindicada.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LojaIndicada service. Represents a row in the &quot;loja_indicada&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.lapidarios.lojaindicada.model.impl.LojaIndicadaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.lapidarios.lojaindicada.model.impl.LojaIndicadaImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see LojaIndicada
 * @see br.com.prodevelopment.lapidarios.lojaindicada.model.impl.LojaIndicadaImpl
 * @see br.com.prodevelopment.lapidarios.lojaindicada.model.impl.LojaIndicadaModelImpl
 * @generated
 */
public interface LojaIndicadaModel extends BaseModel<LojaIndicada>, StagedModel,
	TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loja indicada model instance should use the {@link LojaIndicada} interface instead.
	 */

	/**
	 * Returns the primary key of this loja indicada.
	 *
	 * @return the primary key of this loja indicada
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loja indicada.
	 *
	 * @param primaryKey the primary key of this loja indicada
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loja indicada.
	 *
	 * @return the uuid of this loja indicada
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this loja indicada.
	 *
	 * @param uuid the uuid of this loja indicada
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the loja indicada ID of this loja indicada.
	 *
	 * @return the loja indicada ID of this loja indicada
	 */
	public long getLojaIndicadaId();

	/**
	 * Sets the loja indicada ID of this loja indicada.
	 *
	 * @param lojaIndicadaId the loja indicada ID of this loja indicada
	 */
	public void setLojaIndicadaId(long lojaIndicadaId);

	/**
	 * Returns the company ID of this loja indicada.
	 *
	 * @return the company ID of this loja indicada
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loja indicada.
	 *
	 * @param companyId the company ID of this loja indicada
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this loja indicada.
	 *
	 * @return the group ID of this loja indicada
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this loja indicada.
	 *
	 * @param groupId the group ID of this loja indicada
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this loja indicada.
	 *
	 * @return the create user ID of this loja indicada
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this loja indicada.
	 *
	 * @param createUserId the create user ID of this loja indicada
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this loja indicada.
	 *
	 * @return the create user uuid of this loja indicada
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this loja indicada.
	 *
	 * @param createUserUuid the create user uuid of this loja indicada
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this loja indicada.
	 *
	 * @return the modified user ID of this loja indicada
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this loja indicada.
	 *
	 * @param modifiedUserId the modified user ID of this loja indicada
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this loja indicada.
	 *
	 * @return the modified user uuid of this loja indicada
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this loja indicada.
	 *
	 * @param modifiedUserUuid the modified user uuid of this loja indicada
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this loja indicada.
	 *
	 * @return the create date of this loja indicada
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loja indicada.
	 *
	 * @param createDate the create date of this loja indicada
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loja indicada.
	 *
	 * @return the modified date of this loja indicada
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loja indicada.
	 *
	 * @param modifiedDate the modified date of this loja indicada
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the id loja of this loja indicada.
	 *
	 * @return the id loja of this loja indicada
	 */
	@AutoEscape
	public String getIdLoja();

	/**
	 * Sets the id loja of this loja indicada.
	 *
	 * @param idLoja the id loja of this loja indicada
	 */
	public void setIdLoja(String idLoja);

	/**
	 * Returns the loja indicada atual of this loja indicada.
	 *
	 * @return the loja indicada atual of this loja indicada
	 */
	public Boolean getLojaIndicadaAtual();

	/**
	 * Sets the loja indicada atual of this loja indicada.
	 *
	 * @param lojaIndicadaAtual the loja indicada atual of this loja indicada
	 */
	public void setLojaIndicadaAtual(Boolean lojaIndicadaAtual);

	/**
	 * Returns the status of this loja indicada.
	 *
	 * @return the status of this loja indicada
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this loja indicada was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this loja indicada.
	 *
	 * @return the trash entry created when this loja indicada was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this loja indicada.
	 *
	 * @return the class primary key of the trash entry for this loja indicada
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this loja indicada.
	 *
	 * @return the trash handler for this loja indicada
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this loja indicada is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this loja indicada is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this loja indicada is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this loja indicada is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.lapidarios.lojaindicada.model.LojaIndicada lojaIndicada);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.lapidarios.lojaindicada.model.LojaIndicada> toCacheModel();

	@Override
	public br.com.prodevelopment.lapidarios.lojaindicada.model.LojaIndicada toEscapedModel();

	@Override
	public br.com.prodevelopment.lapidarios.lojaindicada.model.LojaIndicada toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}