/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.lapidarios.evento.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventoInscricao service. Represents a row in the &quot;evento_inscricao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.lapidarios.evento.model.impl.EventoInscricaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.lapidarios.evento.model.impl.EventoInscricaoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see EventoInscricao
 * @see br.com.prodevelopment.lapidarios.evento.model.impl.EventoInscricaoImpl
 * @see br.com.prodevelopment.lapidarios.evento.model.impl.EventoInscricaoModelImpl
 * @generated
 */
public interface EventoInscricaoModel extends BaseModel<EventoInscricao> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evento inscricao model instance should use the {@link EventoInscricao} interface instead.
	 */

	/**
	 * Returns the primary key of this evento inscricao.
	 *
	 * @return the primary key of this evento inscricao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evento inscricao.
	 *
	 * @param primaryKey the primary key of this evento inscricao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this evento inscricao.
	 *
	 * @return the uuid of this evento inscricao
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this evento inscricao.
	 *
	 * @param uuid the uuid of this evento inscricao
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the evento inscricao ID of this evento inscricao.
	 *
	 * @return the evento inscricao ID of this evento inscricao
	 */
	public long getEventoInscricaoId();

	/**
	 * Sets the evento inscricao ID of this evento inscricao.
	 *
	 * @param eventoInscricaoId the evento inscricao ID of this evento inscricao
	 */
	public void setEventoInscricaoId(long eventoInscricaoId);

	/**
	 * Returns the company ID of this evento inscricao.
	 *
	 * @return the company ID of this evento inscricao
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this evento inscricao.
	 *
	 * @param companyId the company ID of this evento inscricao
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this evento inscricao.
	 *
	 * @return the group ID of this evento inscricao
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this evento inscricao.
	 *
	 * @param groupId the group ID of this evento inscricao
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this evento inscricao.
	 *
	 * @return the create user ID of this evento inscricao
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this evento inscricao.
	 *
	 * @param createUserId the create user ID of this evento inscricao
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this evento inscricao.
	 *
	 * @return the create user uuid of this evento inscricao
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this evento inscricao.
	 *
	 * @param createUserUuid the create user uuid of this evento inscricao
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this evento inscricao.
	 *
	 * @return the create date of this evento inscricao
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this evento inscricao.
	 *
	 * @param createDate the create date of this evento inscricao
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the evento agenda ID of this evento inscricao.
	 *
	 * @return the evento agenda ID of this evento inscricao
	 */
	public long getEventoAgendaId();

	/**
	 * Sets the evento agenda ID of this evento inscricao.
	 *
	 * @param eventoAgendaId the evento agenda ID of this evento inscricao
	 */
	public void setEventoAgendaId(long eventoAgendaId);

	/**
	 * Returns the evento ID of this evento inscricao.
	 *
	 * @return the evento ID of this evento inscricao
	 */
	public long getEventoId();

	/**
	 * Sets the evento ID of this evento inscricao.
	 *
	 * @param eventoId the evento ID of this evento inscricao
	 */
	public void setEventoId(long eventoId);

	/**
	 * Returns the user nome of this evento inscricao.
	 *
	 * @return the user nome of this evento inscricao
	 */
	@AutoEscape
	public String getUserNome();

	/**
	 * Sets the user nome of this evento inscricao.
	 *
	 * @param userNome the user nome of this evento inscricao
	 */
	public void setUserNome(String userNome);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.lapidarios.evento.model.EventoInscricao eventoInscricao);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.lapidarios.evento.model.EventoInscricao> toCacheModel();

	@Override
	public br.com.prodevelopment.lapidarios.evento.model.EventoInscricao toEscapedModel();

	@Override
	public br.com.prodevelopment.lapidarios.evento.model.EventoInscricao toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}