/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.associado.model.impl;

import br.com.prodevelopment.associado.model.Associado;
import br.com.prodevelopment.associado.model.AssociadoModel;
import br.com.prodevelopment.associado.model.AssociadoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Associado service. Represents a row in the &quot;associado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.associado.model.AssociadoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssociadoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see AssociadoImpl
 * @see br.com.prodevelopment.associado.model.Associado
 * @see br.com.prodevelopment.associado.model.AssociadoModel
 * @generated
 */
@JSON(strict = true)
public class AssociadoModelImpl extends BaseModelImpl<Associado>
	implements AssociadoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a associado model instance should use the {@link br.com.prodevelopment.associado.model.Associado} interface instead.
	 */
	public static final String TABLE_NAME = "associado";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "associadoId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createUserId", Types.BIGINT },
			{ "modifiedUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "nome", Types.VARCHAR },
			{ "rgInscricaoMun", Types.VARCHAR },
			{ "rgOrgaoEmissor", Types.VARCHAR },
			{ "rgDataEmissao", Types.TIMESTAMP },
			{ "tipoPessoa", Types.VARCHAR },
			{ "cpfCnpj", Types.VARCHAR },
			{ "sexo", Types.VARCHAR },
			{ "estadoCivil", Types.VARCHAR },
			{ "dataNascimento", Types.TIMESTAMP },
			{ "endComLogradouro", Types.VARCHAR },
			{ "endComNumero", Types.VARCHAR },
			{ "endComComplemento", Types.VARCHAR },
			{ "endComCep", Types.VARCHAR },
			{ "endComBairro", Types.VARCHAR },
			{ "endComCidade", Types.VARCHAR },
			{ "endComUf", Types.VARCHAR },
			{ "endComPais", Types.VARCHAR },
			{ "endResLogradouro", Types.VARCHAR },
			{ "endResNumero", Types.VARCHAR },
			{ "endResComplemento", Types.VARCHAR },
			{ "endResCep", Types.VARCHAR },
			{ "endResBairro", Types.VARCHAR },
			{ "endResCidade", Types.VARCHAR },
			{ "endResUf", Types.VARCHAR },
			{ "endResPais", Types.VARCHAR },
			{ "telComDdd", Types.VARCHAR },
			{ "versao", Types.DOUBLE },
			{ "userId", Types.BIGINT },
			{ "observacao", Types.VARCHAR },
			{ "idPolishop", Types.VARCHAR },
			{ "idLojaIndicada", Types.VARCHAR },
			{ "idPatrocinador", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table associado (uuid_ VARCHAR(75) null,associadoId LONG not null primary key,companyId LONG,groupId LONG,createUserId LONG,modifiedUserId LONG,createDate DATE null,modifiedDate DATE null,nome VARCHAR(100) null,rgInscricaoMun VARCHAR(20) null,rgOrgaoEmissor VARCHAR(20) null,rgDataEmissao DATE null,tipoPessoa VARCHAR(2) null,cpfCnpj VARCHAR(20) null,sexo VARCHAR(1) null,estadoCivil VARCHAR(20) null,dataNascimento DATE null,endComLogradouro VARCHAR(100) null,endComNumero VARCHAR(10) null,endComComplemento VARCHAR(50) null,endComCep VARCHAR(10) null,endComBairro VARCHAR(80) null,endComCidade VARCHAR(80) null,endComUf VARCHAR(2) null,endComPais VARCHAR(80) null,endResLogradouro VARCHAR(100) null,endResNumero VARCHAR(10) null,endResComplemento VARCHAR(50) null,endResCep VARCHAR(10) null,endResBairro VARCHAR(80) null,endResCidade VARCHAR(80) null,endResUf VARCHAR(2) null,endResPais VARCHAR(80) null,telComDdd VARCHAR(10) null,versao DOUBLE,userId LONG,observacao VARCHAR(2000) null,idPolishop VARCHAR(75) null,idLojaIndicada VARCHAR(75) null,idPatrocinador VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table associado";
	public static final String ORDER_BY_JPQL = " ORDER BY associado.nome ASC";
	public static final String ORDER_BY_SQL = " ORDER BY associado.nome ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.associado.model.Associado"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.associado.model.Associado"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.associado.model.Associado"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long CPFCNPJ_COLUMN_BITMASK = 2L;
	public static long DATANASCIMENTO_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long IDPOLISHOP_COLUMN_BITMASK = 16L;
	public static long NOME_COLUMN_BITMASK = 32L;
	public static long RGINSCRICAOMUN_COLUMN_BITMASK = 64L;
	public static long USERID_COLUMN_BITMASK = 128L;
	public static long UUID_COLUMN_BITMASK = 256L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Associado toModel(AssociadoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Associado model = new AssociadoImpl();

		model.setUuid(soapModel.getUuid());
		model.setAssociadoId(soapModel.getAssociadoId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateUserId(soapModel.getCreateUserId());
		model.setModifiedUserId(soapModel.getModifiedUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setNome(soapModel.getNome());
		model.setRgInscricaoMun(soapModel.getRgInscricaoMun());
		model.setRgOrgaoEmissor(soapModel.getRgOrgaoEmissor());
		model.setRgDataEmissao(soapModel.getRgDataEmissao());
		model.setTipoPessoa(soapModel.getTipoPessoa());
		model.setCpfCnpj(soapModel.getCpfCnpj());
		model.setSexo(soapModel.getSexo());
		model.setEstadoCivil(soapModel.getEstadoCivil());
		model.setDataNascimento(soapModel.getDataNascimento());
		model.setEndComLogradouro(soapModel.getEndComLogradouro());
		model.setEndComNumero(soapModel.getEndComNumero());
		model.setEndComComplemento(soapModel.getEndComComplemento());
		model.setEndComCep(soapModel.getEndComCep());
		model.setEndComBairro(soapModel.getEndComBairro());
		model.setEndComCidade(soapModel.getEndComCidade());
		model.setEndComUf(soapModel.getEndComUf());
		model.setEndComPais(soapModel.getEndComPais());
		model.setEndResLogradouro(soapModel.getEndResLogradouro());
		model.setEndResNumero(soapModel.getEndResNumero());
		model.setEndResComplemento(soapModel.getEndResComplemento());
		model.setEndResCep(soapModel.getEndResCep());
		model.setEndResBairro(soapModel.getEndResBairro());
		model.setEndResCidade(soapModel.getEndResCidade());
		model.setEndResUf(soapModel.getEndResUf());
		model.setEndResPais(soapModel.getEndResPais());
		model.setTelComDdd(soapModel.getTelComDdd());
		model.setVersao(soapModel.getVersao());
		model.setUserId(soapModel.getUserId());
		model.setObservacao(soapModel.getObservacao());
		model.setIdPolishop(soapModel.getIdPolishop());
		model.setIdLojaIndicada(soapModel.getIdLojaIndicada());
		model.setIdPatrocinador(soapModel.getIdPatrocinador());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Associado> toModels(AssociadoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Associado> models = new ArrayList<Associado>(soapModels.length);

		for (AssociadoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.associado.model.Associado"));

	public AssociadoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _associadoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssociadoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _associadoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Associado.class;
	}

	@Override
	public String getModelClassName() {
		return Associado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("associadoId", getAssociadoId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createUserId", getCreateUserId());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("nome", getNome());
		attributes.put("rgInscricaoMun", getRgInscricaoMun());
		attributes.put("rgOrgaoEmissor", getRgOrgaoEmissor());
		attributes.put("rgDataEmissao", getRgDataEmissao());
		attributes.put("tipoPessoa", getTipoPessoa());
		attributes.put("cpfCnpj", getCpfCnpj());
		attributes.put("sexo", getSexo());
		attributes.put("estadoCivil", getEstadoCivil());
		attributes.put("dataNascimento", getDataNascimento());
		attributes.put("endComLogradouro", getEndComLogradouro());
		attributes.put("endComNumero", getEndComNumero());
		attributes.put("endComComplemento", getEndComComplemento());
		attributes.put("endComCep", getEndComCep());
		attributes.put("endComBairro", getEndComBairro());
		attributes.put("endComCidade", getEndComCidade());
		attributes.put("endComUf", getEndComUf());
		attributes.put("endComPais", getEndComPais());
		attributes.put("endResLogradouro", getEndResLogradouro());
		attributes.put("endResNumero", getEndResNumero());
		attributes.put("endResComplemento", getEndResComplemento());
		attributes.put("endResCep", getEndResCep());
		attributes.put("endResBairro", getEndResBairro());
		attributes.put("endResCidade", getEndResCidade());
		attributes.put("endResUf", getEndResUf());
		attributes.put("endResPais", getEndResPais());
		attributes.put("telComDdd", getTelComDdd());
		attributes.put("versao", getVersao());
		attributes.put("userId", getUserId());
		attributes.put("observacao", getObservacao());
		attributes.put("idPolishop", getIdPolishop());
		attributes.put("idLojaIndicada", getIdLojaIndicada());
		attributes.put("idPatrocinador", getIdPatrocinador());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long associadoId = (Long)attributes.get("associadoId");

		if (associadoId != null) {
			setAssociadoId(associadoId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long createUserId = (Long)attributes.get("createUserId");

		if (createUserId != null) {
			setCreateUserId(createUserId);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String rgInscricaoMun = (String)attributes.get("rgInscricaoMun");

		if (rgInscricaoMun != null) {
			setRgInscricaoMun(rgInscricaoMun);
		}

		String rgOrgaoEmissor = (String)attributes.get("rgOrgaoEmissor");

		if (rgOrgaoEmissor != null) {
			setRgOrgaoEmissor(rgOrgaoEmissor);
		}

		Date rgDataEmissao = (Date)attributes.get("rgDataEmissao");

		if (rgDataEmissao != null) {
			setRgDataEmissao(rgDataEmissao);
		}

		String tipoPessoa = (String)attributes.get("tipoPessoa");

		if (tipoPessoa != null) {
			setTipoPessoa(tipoPessoa);
		}

		String cpfCnpj = (String)attributes.get("cpfCnpj");

		if (cpfCnpj != null) {
			setCpfCnpj(cpfCnpj);
		}

		String sexo = (String)attributes.get("sexo");

		if (sexo != null) {
			setSexo(sexo);
		}

		String estadoCivil = (String)attributes.get("estadoCivil");

		if (estadoCivil != null) {
			setEstadoCivil(estadoCivil);
		}

		Date dataNascimento = (Date)attributes.get("dataNascimento");

		if (dataNascimento != null) {
			setDataNascimento(dataNascimento);
		}

		String endComLogradouro = (String)attributes.get("endComLogradouro");

		if (endComLogradouro != null) {
			setEndComLogradouro(endComLogradouro);
		}

		String endComNumero = (String)attributes.get("endComNumero");

		if (endComNumero != null) {
			setEndComNumero(endComNumero);
		}

		String endComComplemento = (String)attributes.get("endComComplemento");

		if (endComComplemento != null) {
			setEndComComplemento(endComComplemento);
		}

		String endComCep = (String)attributes.get("endComCep");

		if (endComCep != null) {
			setEndComCep(endComCep);
		}

		String endComBairro = (String)attributes.get("endComBairro");

		if (endComBairro != null) {
			setEndComBairro(endComBairro);
		}

		String endComCidade = (String)attributes.get("endComCidade");

		if (endComCidade != null) {
			setEndComCidade(endComCidade);
		}

		String endComUf = (String)attributes.get("endComUf");

		if (endComUf != null) {
			setEndComUf(endComUf);
		}

		String endComPais = (String)attributes.get("endComPais");

		if (endComPais != null) {
			setEndComPais(endComPais);
		}

		String endResLogradouro = (String)attributes.get("endResLogradouro");

		if (endResLogradouro != null) {
			setEndResLogradouro(endResLogradouro);
		}

		String endResNumero = (String)attributes.get("endResNumero");

		if (endResNumero != null) {
			setEndResNumero(endResNumero);
		}

		String endResComplemento = (String)attributes.get("endResComplemento");

		if (endResComplemento != null) {
			setEndResComplemento(endResComplemento);
		}

		String endResCep = (String)attributes.get("endResCep");

		if (endResCep != null) {
			setEndResCep(endResCep);
		}

		String endResBairro = (String)attributes.get("endResBairro");

		if (endResBairro != null) {
			setEndResBairro(endResBairro);
		}

		String endResCidade = (String)attributes.get("endResCidade");

		if (endResCidade != null) {
			setEndResCidade(endResCidade);
		}

		String endResUf = (String)attributes.get("endResUf");

		if (endResUf != null) {
			setEndResUf(endResUf);
		}

		String endResPais = (String)attributes.get("endResPais");

		if (endResPais != null) {
			setEndResPais(endResPais);
		}

		String telComDdd = (String)attributes.get("telComDdd");

		if (telComDdd != null) {
			setTelComDdd(telComDdd);
		}

		Double versao = (Double)attributes.get("versao");

		if (versao != null) {
			setVersao(versao);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String observacao = (String)attributes.get("observacao");

		if (observacao != null) {
			setObservacao(observacao);
		}

		String idPolishop = (String)attributes.get("idPolishop");

		if (idPolishop != null) {
			setIdPolishop(idPolishop);
		}

		String idLojaIndicada = (String)attributes.get("idLojaIndicada");

		if (idLojaIndicada != null) {
			setIdLojaIndicada(idLojaIndicada);
		}

		String idPatrocinador = (String)attributes.get("idPatrocinador");

		if (idPatrocinador != null) {
			setIdPatrocinador(idPatrocinador);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAssociadoId() {
		return _associadoId;
	}

	@Override
	public void setAssociadoId(long associadoId) {
		_associadoId = associadoId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCreateUserId() {
		return _createUserId;
	}

	@Override
	public void setCreateUserId(long createUserId) {
		_createUserId = createUserId;
	}

	@Override
	public String getCreateUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreateUserId(), "uuid",
			_createUserUuid);
	}

	@Override
	public void setCreateUserUuid(String createUserUuid) {
		_createUserUuid = createUserUuid;
	}

	@JSON
	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_columnBitmask = -1L;

		if (_originalNome == null) {
			_originalNome = _nome;
		}

		_nome = nome;
	}

	public String getOriginalNome() {
		return GetterUtil.getString(_originalNome);
	}

	@JSON
	@Override
	public String getRgInscricaoMun() {
		if (_rgInscricaoMun == null) {
			return StringPool.BLANK;
		}
		else {
			return _rgInscricaoMun;
		}
	}

	@Override
	public void setRgInscricaoMun(String rgInscricaoMun) {
		_columnBitmask |= RGINSCRICAOMUN_COLUMN_BITMASK;

		if (_originalRgInscricaoMun == null) {
			_originalRgInscricaoMun = _rgInscricaoMun;
		}

		_rgInscricaoMun = rgInscricaoMun;
	}

	public String getOriginalRgInscricaoMun() {
		return GetterUtil.getString(_originalRgInscricaoMun);
	}

	@JSON
	@Override
	public String getRgOrgaoEmissor() {
		if (_rgOrgaoEmissor == null) {
			return StringPool.BLANK;
		}
		else {
			return _rgOrgaoEmissor;
		}
	}

	@Override
	public void setRgOrgaoEmissor(String rgOrgaoEmissor) {
		_rgOrgaoEmissor = rgOrgaoEmissor;
	}

	@JSON
	@Override
	public Date getRgDataEmissao() {
		return _rgDataEmissao;
	}

	@Override
	public void setRgDataEmissao(Date rgDataEmissao) {
		_rgDataEmissao = rgDataEmissao;
	}

	@JSON
	@Override
	public String getTipoPessoa() {
		if (_tipoPessoa == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoPessoa;
		}
	}

	@Override
	public void setTipoPessoa(String tipoPessoa) {
		_tipoPessoa = tipoPessoa;
	}

	@JSON
	@Override
	public String getCpfCnpj() {
		if (_cpfCnpj == null) {
			return StringPool.BLANK;
		}
		else {
			return _cpfCnpj;
		}
	}

	@Override
	public void setCpfCnpj(String cpfCnpj) {
		_columnBitmask |= CPFCNPJ_COLUMN_BITMASK;

		if (_originalCpfCnpj == null) {
			_originalCpfCnpj = _cpfCnpj;
		}

		_cpfCnpj = cpfCnpj;
	}

	public String getOriginalCpfCnpj() {
		return GetterUtil.getString(_originalCpfCnpj);
	}

	@JSON
	@Override
	public String getSexo() {
		if (_sexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _sexo;
		}
	}

	@Override
	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	@JSON
	@Override
	public String getEstadoCivil() {
		if (_estadoCivil == null) {
			return StringPool.BLANK;
		}
		else {
			return _estadoCivil;
		}
	}

	@Override
	public void setEstadoCivil(String estadoCivil) {
		_estadoCivil = estadoCivil;
	}

	@JSON
	@Override
	public Date getDataNascimento() {
		return _dataNascimento;
	}

	@Override
	public void setDataNascimento(Date dataNascimento) {
		_columnBitmask |= DATANASCIMENTO_COLUMN_BITMASK;

		if (_originalDataNascimento == null) {
			_originalDataNascimento = _dataNascimento;
		}

		_dataNascimento = dataNascimento;
	}

	public Date getOriginalDataNascimento() {
		return _originalDataNascimento;
	}

	@JSON
	@Override
	public String getEndComLogradouro() {
		if (_endComLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComLogradouro;
		}
	}

	@Override
	public void setEndComLogradouro(String endComLogradouro) {
		_endComLogradouro = endComLogradouro;
	}

	@JSON
	@Override
	public String getEndComNumero() {
		if (_endComNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComNumero;
		}
	}

	@Override
	public void setEndComNumero(String endComNumero) {
		_endComNumero = endComNumero;
	}

	@JSON
	@Override
	public String getEndComComplemento() {
		if (_endComComplemento == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComComplemento;
		}
	}

	@Override
	public void setEndComComplemento(String endComComplemento) {
		_endComComplemento = endComComplemento;
	}

	@JSON
	@Override
	public String getEndComCep() {
		if (_endComCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComCep;
		}
	}

	@Override
	public void setEndComCep(String endComCep) {
		_endComCep = endComCep;
	}

	@JSON
	@Override
	public String getEndComBairro() {
		if (_endComBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComBairro;
		}
	}

	@Override
	public void setEndComBairro(String endComBairro) {
		_endComBairro = endComBairro;
	}

	@JSON
	@Override
	public String getEndComCidade() {
		if (_endComCidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComCidade;
		}
	}

	@Override
	public void setEndComCidade(String endComCidade) {
		_endComCidade = endComCidade;
	}

	@JSON
	@Override
	public String getEndComUf() {
		if (_endComUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComUf;
		}
	}

	@Override
	public void setEndComUf(String endComUf) {
		_endComUf = endComUf;
	}

	@JSON
	@Override
	public String getEndComPais() {
		if (_endComPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComPais;
		}
	}

	@Override
	public void setEndComPais(String endComPais) {
		_endComPais = endComPais;
	}

	@JSON
	@Override
	public String getEndResLogradouro() {
		if (_endResLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResLogradouro;
		}
	}

	@Override
	public void setEndResLogradouro(String endResLogradouro) {
		_endResLogradouro = endResLogradouro;
	}

	@JSON
	@Override
	public String getEndResNumero() {
		if (_endResNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResNumero;
		}
	}

	@Override
	public void setEndResNumero(String endResNumero) {
		_endResNumero = endResNumero;
	}

	@JSON
	@Override
	public String getEndResComplemento() {
		if (_endResComplemento == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResComplemento;
		}
	}

	@Override
	public void setEndResComplemento(String endResComplemento) {
		_endResComplemento = endResComplemento;
	}

	@JSON
	@Override
	public String getEndResCep() {
		if (_endResCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResCep;
		}
	}

	@Override
	public void setEndResCep(String endResCep) {
		_endResCep = endResCep;
	}

	@JSON
	@Override
	public String getEndResBairro() {
		if (_endResBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResBairro;
		}
	}

	@Override
	public void setEndResBairro(String endResBairro) {
		_endResBairro = endResBairro;
	}

	@JSON
	@Override
	public String getEndResCidade() {
		if (_endResCidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResCidade;
		}
	}

	@Override
	public void setEndResCidade(String endResCidade) {
		_endResCidade = endResCidade;
	}

	@JSON
	@Override
	public String getEndResUf() {
		if (_endResUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResUf;
		}
	}

	@Override
	public void setEndResUf(String endResUf) {
		_endResUf = endResUf;
	}

	@JSON
	@Override
	public String getEndResPais() {
		if (_endResPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResPais;
		}
	}

	@Override
	public void setEndResPais(String endResPais) {
		_endResPais = endResPais;
	}

	@JSON
	@Override
	public String getTelComDdd() {
		if (_telComDdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _telComDdd;
		}
	}

	@Override
	public void setTelComDdd(String telComDdd) {
		_telComDdd = telComDdd;
	}

	@JSON
	@Override
	public double getVersao() {
		return _versao;
	}

	@Override
	public void setVersao(double versao) {
		_versao = versao;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getObservacao() {
		if (_observacao == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacao;
		}
	}

	@Override
	public void setObservacao(String observacao) {
		_observacao = observacao;
	}

	@JSON
	@Override
	public String getIdPolishop() {
		if (_idPolishop == null) {
			return StringPool.BLANK;
		}
		else {
			return _idPolishop;
		}
	}

	@Override
	public void setIdPolishop(String idPolishop) {
		_columnBitmask |= IDPOLISHOP_COLUMN_BITMASK;

		if (_originalIdPolishop == null) {
			_originalIdPolishop = _idPolishop;
		}

		_idPolishop = idPolishop;
	}

	public String getOriginalIdPolishop() {
		return GetterUtil.getString(_originalIdPolishop);
	}

	@JSON
	@Override
	public String getIdLojaIndicada() {
		if (_idLojaIndicada == null) {
			return StringPool.BLANK;
		}
		else {
			return _idLojaIndicada;
		}
	}

	@Override
	public void setIdLojaIndicada(String idLojaIndicada) {
		_idLojaIndicada = idLojaIndicada;
	}

	@JSON
	@Override
	public String getIdPatrocinador() {
		if (_idPatrocinador == null) {
			return StringPool.BLANK;
		}
		else {
			return _idPatrocinador;
		}
	}

	@Override
	public void setIdPatrocinador(String idPatrocinador) {
		_idPatrocinador = idPatrocinador;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Associado.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Associado.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Associado toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Associado)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssociadoImpl associadoImpl = new AssociadoImpl();

		associadoImpl.setUuid(getUuid());
		associadoImpl.setAssociadoId(getAssociadoId());
		associadoImpl.setCompanyId(getCompanyId());
		associadoImpl.setGroupId(getGroupId());
		associadoImpl.setCreateUserId(getCreateUserId());
		associadoImpl.setModifiedUserId(getModifiedUserId());
		associadoImpl.setCreateDate(getCreateDate());
		associadoImpl.setModifiedDate(getModifiedDate());
		associadoImpl.setNome(getNome());
		associadoImpl.setRgInscricaoMun(getRgInscricaoMun());
		associadoImpl.setRgOrgaoEmissor(getRgOrgaoEmissor());
		associadoImpl.setRgDataEmissao(getRgDataEmissao());
		associadoImpl.setTipoPessoa(getTipoPessoa());
		associadoImpl.setCpfCnpj(getCpfCnpj());
		associadoImpl.setSexo(getSexo());
		associadoImpl.setEstadoCivil(getEstadoCivil());
		associadoImpl.setDataNascimento(getDataNascimento());
		associadoImpl.setEndComLogradouro(getEndComLogradouro());
		associadoImpl.setEndComNumero(getEndComNumero());
		associadoImpl.setEndComComplemento(getEndComComplemento());
		associadoImpl.setEndComCep(getEndComCep());
		associadoImpl.setEndComBairro(getEndComBairro());
		associadoImpl.setEndComCidade(getEndComCidade());
		associadoImpl.setEndComUf(getEndComUf());
		associadoImpl.setEndComPais(getEndComPais());
		associadoImpl.setEndResLogradouro(getEndResLogradouro());
		associadoImpl.setEndResNumero(getEndResNumero());
		associadoImpl.setEndResComplemento(getEndResComplemento());
		associadoImpl.setEndResCep(getEndResCep());
		associadoImpl.setEndResBairro(getEndResBairro());
		associadoImpl.setEndResCidade(getEndResCidade());
		associadoImpl.setEndResUf(getEndResUf());
		associadoImpl.setEndResPais(getEndResPais());
		associadoImpl.setTelComDdd(getTelComDdd());
		associadoImpl.setVersao(getVersao());
		associadoImpl.setUserId(getUserId());
		associadoImpl.setObservacao(getObservacao());
		associadoImpl.setIdPolishop(getIdPolishop());
		associadoImpl.setIdLojaIndicada(getIdLojaIndicada());
		associadoImpl.setIdPatrocinador(getIdPatrocinador());

		associadoImpl.resetOriginalValues();

		return associadoImpl;
	}

	@Override
	public int compareTo(Associado associado) {
		int value = 0;

		value = getNome().compareTo(associado.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Associado)) {
			return false;
		}

		Associado associado = (Associado)obj;

		long primaryKey = associado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AssociadoModelImpl associadoModelImpl = this;

		associadoModelImpl._originalUuid = associadoModelImpl._uuid;

		associadoModelImpl._originalCompanyId = associadoModelImpl._companyId;

		associadoModelImpl._setOriginalCompanyId = false;

		associadoModelImpl._originalGroupId = associadoModelImpl._groupId;

		associadoModelImpl._setOriginalGroupId = false;

		associadoModelImpl._originalNome = associadoModelImpl._nome;

		associadoModelImpl._originalRgInscricaoMun = associadoModelImpl._rgInscricaoMun;

		associadoModelImpl._originalCpfCnpj = associadoModelImpl._cpfCnpj;

		associadoModelImpl._originalDataNascimento = associadoModelImpl._dataNascimento;

		associadoModelImpl._originalUserId = associadoModelImpl._userId;

		associadoModelImpl._setOriginalUserId = false;

		associadoModelImpl._originalIdPolishop = associadoModelImpl._idPolishop;

		associadoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Associado> toCacheModel() {
		AssociadoCacheModel associadoCacheModel = new AssociadoCacheModel();

		associadoCacheModel.uuid = getUuid();

		String uuid = associadoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			associadoCacheModel.uuid = null;
		}

		associadoCacheModel.associadoId = getAssociadoId();

		associadoCacheModel.companyId = getCompanyId();

		associadoCacheModel.groupId = getGroupId();

		associadoCacheModel.createUserId = getCreateUserId();

		associadoCacheModel.modifiedUserId = getModifiedUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			associadoCacheModel.createDate = createDate.getTime();
		}
		else {
			associadoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			associadoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			associadoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		associadoCacheModel.nome = getNome();

		String nome = associadoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			associadoCacheModel.nome = null;
		}

		associadoCacheModel.rgInscricaoMun = getRgInscricaoMun();

		String rgInscricaoMun = associadoCacheModel.rgInscricaoMun;

		if ((rgInscricaoMun != null) && (rgInscricaoMun.length() == 0)) {
			associadoCacheModel.rgInscricaoMun = null;
		}

		associadoCacheModel.rgOrgaoEmissor = getRgOrgaoEmissor();

		String rgOrgaoEmissor = associadoCacheModel.rgOrgaoEmissor;

		if ((rgOrgaoEmissor != null) && (rgOrgaoEmissor.length() == 0)) {
			associadoCacheModel.rgOrgaoEmissor = null;
		}

		Date rgDataEmissao = getRgDataEmissao();

		if (rgDataEmissao != null) {
			associadoCacheModel.rgDataEmissao = rgDataEmissao.getTime();
		}
		else {
			associadoCacheModel.rgDataEmissao = Long.MIN_VALUE;
		}

		associadoCacheModel.tipoPessoa = getTipoPessoa();

		String tipoPessoa = associadoCacheModel.tipoPessoa;

		if ((tipoPessoa != null) && (tipoPessoa.length() == 0)) {
			associadoCacheModel.tipoPessoa = null;
		}

		associadoCacheModel.cpfCnpj = getCpfCnpj();

		String cpfCnpj = associadoCacheModel.cpfCnpj;

		if ((cpfCnpj != null) && (cpfCnpj.length() == 0)) {
			associadoCacheModel.cpfCnpj = null;
		}

		associadoCacheModel.sexo = getSexo();

		String sexo = associadoCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			associadoCacheModel.sexo = null;
		}

		associadoCacheModel.estadoCivil = getEstadoCivil();

		String estadoCivil = associadoCacheModel.estadoCivil;

		if ((estadoCivil != null) && (estadoCivil.length() == 0)) {
			associadoCacheModel.estadoCivil = null;
		}

		Date dataNascimento = getDataNascimento();

		if (dataNascimento != null) {
			associadoCacheModel.dataNascimento = dataNascimento.getTime();
		}
		else {
			associadoCacheModel.dataNascimento = Long.MIN_VALUE;
		}

		associadoCacheModel.endComLogradouro = getEndComLogradouro();

		String endComLogradouro = associadoCacheModel.endComLogradouro;

		if ((endComLogradouro != null) && (endComLogradouro.length() == 0)) {
			associadoCacheModel.endComLogradouro = null;
		}

		associadoCacheModel.endComNumero = getEndComNumero();

		String endComNumero = associadoCacheModel.endComNumero;

		if ((endComNumero != null) && (endComNumero.length() == 0)) {
			associadoCacheModel.endComNumero = null;
		}

		associadoCacheModel.endComComplemento = getEndComComplemento();

		String endComComplemento = associadoCacheModel.endComComplemento;

		if ((endComComplemento != null) && (endComComplemento.length() == 0)) {
			associadoCacheModel.endComComplemento = null;
		}

		associadoCacheModel.endComCep = getEndComCep();

		String endComCep = associadoCacheModel.endComCep;

		if ((endComCep != null) && (endComCep.length() == 0)) {
			associadoCacheModel.endComCep = null;
		}

		associadoCacheModel.endComBairro = getEndComBairro();

		String endComBairro = associadoCacheModel.endComBairro;

		if ((endComBairro != null) && (endComBairro.length() == 0)) {
			associadoCacheModel.endComBairro = null;
		}

		associadoCacheModel.endComCidade = getEndComCidade();

		String endComCidade = associadoCacheModel.endComCidade;

		if ((endComCidade != null) && (endComCidade.length() == 0)) {
			associadoCacheModel.endComCidade = null;
		}

		associadoCacheModel.endComUf = getEndComUf();

		String endComUf = associadoCacheModel.endComUf;

		if ((endComUf != null) && (endComUf.length() == 0)) {
			associadoCacheModel.endComUf = null;
		}

		associadoCacheModel.endComPais = getEndComPais();

		String endComPais = associadoCacheModel.endComPais;

		if ((endComPais != null) && (endComPais.length() == 0)) {
			associadoCacheModel.endComPais = null;
		}

		associadoCacheModel.endResLogradouro = getEndResLogradouro();

		String endResLogradouro = associadoCacheModel.endResLogradouro;

		if ((endResLogradouro != null) && (endResLogradouro.length() == 0)) {
			associadoCacheModel.endResLogradouro = null;
		}

		associadoCacheModel.endResNumero = getEndResNumero();

		String endResNumero = associadoCacheModel.endResNumero;

		if ((endResNumero != null) && (endResNumero.length() == 0)) {
			associadoCacheModel.endResNumero = null;
		}

		associadoCacheModel.endResComplemento = getEndResComplemento();

		String endResComplemento = associadoCacheModel.endResComplemento;

		if ((endResComplemento != null) && (endResComplemento.length() == 0)) {
			associadoCacheModel.endResComplemento = null;
		}

		associadoCacheModel.endResCep = getEndResCep();

		String endResCep = associadoCacheModel.endResCep;

		if ((endResCep != null) && (endResCep.length() == 0)) {
			associadoCacheModel.endResCep = null;
		}

		associadoCacheModel.endResBairro = getEndResBairro();

		String endResBairro = associadoCacheModel.endResBairro;

		if ((endResBairro != null) && (endResBairro.length() == 0)) {
			associadoCacheModel.endResBairro = null;
		}

		associadoCacheModel.endResCidade = getEndResCidade();

		String endResCidade = associadoCacheModel.endResCidade;

		if ((endResCidade != null) && (endResCidade.length() == 0)) {
			associadoCacheModel.endResCidade = null;
		}

		associadoCacheModel.endResUf = getEndResUf();

		String endResUf = associadoCacheModel.endResUf;

		if ((endResUf != null) && (endResUf.length() == 0)) {
			associadoCacheModel.endResUf = null;
		}

		associadoCacheModel.endResPais = getEndResPais();

		String endResPais = associadoCacheModel.endResPais;

		if ((endResPais != null) && (endResPais.length() == 0)) {
			associadoCacheModel.endResPais = null;
		}

		associadoCacheModel.telComDdd = getTelComDdd();

		String telComDdd = associadoCacheModel.telComDdd;

		if ((telComDdd != null) && (telComDdd.length() == 0)) {
			associadoCacheModel.telComDdd = null;
		}

		associadoCacheModel.versao = getVersao();

		associadoCacheModel.userId = getUserId();

		associadoCacheModel.observacao = getObservacao();

		String observacao = associadoCacheModel.observacao;

		if ((observacao != null) && (observacao.length() == 0)) {
			associadoCacheModel.observacao = null;
		}

		associadoCacheModel.idPolishop = getIdPolishop();

		String idPolishop = associadoCacheModel.idPolishop;

		if ((idPolishop != null) && (idPolishop.length() == 0)) {
			associadoCacheModel.idPolishop = null;
		}

		associadoCacheModel.idLojaIndicada = getIdLojaIndicada();

		String idLojaIndicada = associadoCacheModel.idLojaIndicada;

		if ((idLojaIndicada != null) && (idLojaIndicada.length() == 0)) {
			associadoCacheModel.idLojaIndicada = null;
		}

		associadoCacheModel.idPatrocinador = getIdPatrocinador();

		String idPatrocinador = associadoCacheModel.idPatrocinador;

		if ((idPatrocinador != null) && (idPatrocinador.length() == 0)) {
			associadoCacheModel.idPatrocinador = null;
		}

		return associadoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(81);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", associadoId=");
		sb.append(getAssociadoId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createUserId=");
		sb.append(getCreateUserId());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", rgInscricaoMun=");
		sb.append(getRgInscricaoMun());
		sb.append(", rgOrgaoEmissor=");
		sb.append(getRgOrgaoEmissor());
		sb.append(", rgDataEmissao=");
		sb.append(getRgDataEmissao());
		sb.append(", tipoPessoa=");
		sb.append(getTipoPessoa());
		sb.append(", cpfCnpj=");
		sb.append(getCpfCnpj());
		sb.append(", sexo=");
		sb.append(getSexo());
		sb.append(", estadoCivil=");
		sb.append(getEstadoCivil());
		sb.append(", dataNascimento=");
		sb.append(getDataNascimento());
		sb.append(", endComLogradouro=");
		sb.append(getEndComLogradouro());
		sb.append(", endComNumero=");
		sb.append(getEndComNumero());
		sb.append(", endComComplemento=");
		sb.append(getEndComComplemento());
		sb.append(", endComCep=");
		sb.append(getEndComCep());
		sb.append(", endComBairro=");
		sb.append(getEndComBairro());
		sb.append(", endComCidade=");
		sb.append(getEndComCidade());
		sb.append(", endComUf=");
		sb.append(getEndComUf());
		sb.append(", endComPais=");
		sb.append(getEndComPais());
		sb.append(", endResLogradouro=");
		sb.append(getEndResLogradouro());
		sb.append(", endResNumero=");
		sb.append(getEndResNumero());
		sb.append(", endResComplemento=");
		sb.append(getEndResComplemento());
		sb.append(", endResCep=");
		sb.append(getEndResCep());
		sb.append(", endResBairro=");
		sb.append(getEndResBairro());
		sb.append(", endResCidade=");
		sb.append(getEndResCidade());
		sb.append(", endResUf=");
		sb.append(getEndResUf());
		sb.append(", endResPais=");
		sb.append(getEndResPais());
		sb.append(", telComDdd=");
		sb.append(getTelComDdd());
		sb.append(", versao=");
		sb.append(getVersao());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", observacao=");
		sb.append(getObservacao());
		sb.append(", idPolishop=");
		sb.append(getIdPolishop());
		sb.append(", idLojaIndicada=");
		sb.append(getIdLojaIndicada());
		sb.append(", idPatrocinador=");
		sb.append(getIdPatrocinador());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(124);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.associado.model.Associado");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>associadoId</column-name><column-value><![CDATA[");
		sb.append(getAssociadoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createUserId</column-name><column-value><![CDATA[");
		sb.append(getCreateUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgInscricaoMun</column-name><column-value><![CDATA[");
		sb.append(getRgInscricaoMun());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgOrgaoEmissor</column-name><column-value><![CDATA[");
		sb.append(getRgOrgaoEmissor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgDataEmissao</column-name><column-value><![CDATA[");
		sb.append(getRgDataEmissao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoPessoa</column-name><column-value><![CDATA[");
		sb.append(getTipoPessoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cpfCnpj</column-name><column-value><![CDATA[");
		sb.append(getCpfCnpj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexo</column-name><column-value><![CDATA[");
		sb.append(getSexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoCivil</column-name><column-value><![CDATA[");
		sb.append(getEstadoCivil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataNascimento</column-name><column-value><![CDATA[");
		sb.append(getDataNascimento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndComLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComNumero</column-name><column-value><![CDATA[");
		sb.append(getEndComNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComComplemento</column-name><column-value><![CDATA[");
		sb.append(getEndComComplemento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCep</column-name><column-value><![CDATA[");
		sb.append(getEndComCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComBairro</column-name><column-value><![CDATA[");
		sb.append(getEndComBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCidade</column-name><column-value><![CDATA[");
		sb.append(getEndComCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComUf</column-name><column-value><![CDATA[");
		sb.append(getEndComUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComPais</column-name><column-value><![CDATA[");
		sb.append(getEndComPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndResLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResNumero</column-name><column-value><![CDATA[");
		sb.append(getEndResNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResComplemento</column-name><column-value><![CDATA[");
		sb.append(getEndResComplemento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCep</column-name><column-value><![CDATA[");
		sb.append(getEndResCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResBairro</column-name><column-value><![CDATA[");
		sb.append(getEndResBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCidade</column-name><column-value><![CDATA[");
		sb.append(getEndResCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResUf</column-name><column-value><![CDATA[");
		sb.append(getEndResUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResPais</column-name><column-value><![CDATA[");
		sb.append(getEndResPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telComDdd</column-name><column-value><![CDATA[");
		sb.append(getTelComDdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versao</column-name><column-value><![CDATA[");
		sb.append(getVersao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacao</column-name><column-value><![CDATA[");
		sb.append(getObservacao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idPolishop</column-name><column-value><![CDATA[");
		sb.append(getIdPolishop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idLojaIndicada</column-name><column-value><![CDATA[");
		sb.append(getIdLojaIndicada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idPatrocinador</column-name><column-value><![CDATA[");
		sb.append(getIdPatrocinador());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Associado.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Associado.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _associadoId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _createUserId;
	private String _createUserUuid;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _nome;
	private String _originalNome;
	private String _rgInscricaoMun;
	private String _originalRgInscricaoMun;
	private String _rgOrgaoEmissor;
	private Date _rgDataEmissao;
	private String _tipoPessoa;
	private String _cpfCnpj;
	private String _originalCpfCnpj;
	private String _sexo;
	private String _estadoCivil;
	private Date _dataNascimento;
	private Date _originalDataNascimento;
	private String _endComLogradouro;
	private String _endComNumero;
	private String _endComComplemento;
	private String _endComCep;
	private String _endComBairro;
	private String _endComCidade;
	private String _endComUf;
	private String _endComPais;
	private String _endResLogradouro;
	private String _endResNumero;
	private String _endResComplemento;
	private String _endResCep;
	private String _endResBairro;
	private String _endResCidade;
	private String _endResUf;
	private String _endResPais;
	private String _telComDdd;
	private double _versao;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _observacao;
	private String _idPolishop;
	private String _originalIdPolishop;
	private String _idLojaIndicada;
	private String _idPatrocinador;
	private long _columnBitmask;
	private Associado _escapedModel;
}